### ISSUE TITLE
Breaks down on a big(ish) input

### ISSUE THREAD

**Issue by sashakolpakov** [bottine/vinberg#39]
This input

[  4 -2 0 0 0 0 0 0 0 0 0 0 0 0 0;
  -2 4 -2 2 0 0 0 0 0 0 0 0 -1 0 0;
    0 -2 4 0 0 2 0 0 0 0 0 0 2 0 0;
    0 2 0 4 2 2 0 0 0 0 0 0 0 0 0;
    0 0 0 2 4 2 0 0 2 1 0 0 0 0 0;
    0 0 2 2 2 4 2 2 1 2 0 0 1 0 0;
    0 0 0 0 0 2 4 2 0 2 0 0 0 0 0;
    0 0 0 0 0 2 2 4 0 2 0 0 1 0 0;
    0 0 0 0 2 1 0 0 4 2 0 0 0 0 0;
    0 0 0 0 1 2 2 2 2 4 2 2 1 0 0;
    0 0 0 0 0 0 0 0 0 2 4 2 2 0 0;
    0 0 0 0 0 0 0 0 0 2 2 4 1 0 0;
    0 -1 2 0 0 1 0 1 0 1 2 1 4 0 0;
    0 0 0 0 0 0 0 0 0 0 0 0 0 0  2;
    0 0 0 0 0 0 0 0 0 0 0 0 0 2  0  ]

produces the following output

[ Info: Initialized root iterator.
[ Info: Got all roots at distance zero.
[ Info: Starting with 28 candidate roots (at distance zero) for fundamental cone.
[ Info: Returning 14 cone roots.
[ Info: Got the roots of a fundamental cone.
[ Info:                          : [-1, -2, -4, 0, -2, 4, -1, -2, 0, 0, -1, 0, 2, 0, 0].
[ Info:                          : [-1, -2, -3, 0, -2, 4, -1, -2, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [-1, -2, -3, 0, -2, 4, 0, 0, 2, -4, 1, 2, 0, 0, 0].
[ Info:                          : [-1, -2, -2, 1, -2, 2, -1, 0, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [-1, -2, -2, 1, -2, 2, 0, 0, 2, -2, 1, 0, 0, 0, 0].
[ Info:                          : [-1, -2, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [0, 0, -1, -1, 0, 2, -1, 0, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [0, 0, -1, -1, 0, 2, 0, 0, 0, -2, 1, 0, 0, 0, 0].
[ Info:                          : [0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0].
[ Info:                          : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0].
[ Info:                          : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1].
[ Info: Built the corresponding Coxeter diagram.
[ Info: Found new satisfying root: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0].
[ Info: Found new satisfying root: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0].
[ Info: Found new satisfying root: [0, 0, 1, 1, 0, -2, 1, 0, 0, 0, 0, 0, 0, 1, 0].
[ Info: Found new satisfying root: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0].
[ Info: Found new satisfying root: [0, 0, 1, 1, 0, -2, 0, 0, 0, 2, -1, 0, 0, 1, 0].
[ Info: Found new satisfying root: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0].
[ Info: Found new satisfying root: [1, 2, 4, 0, 2, -4, 1, 2, 0, 0, 1, 0, -2, 1, 0].
[ Info: Found new satisfying root: [1, 2, 3, 0, 2, -4, 0, 0, -2, 4, -1, -2, 0, 1, 0].
[ Info: Found new satisfying root: [1, 2, 2, -1, 2, -2, 0, 0, -2, 2, -1, 0, 0, 1, 0].
[ Info: Found new satisfying root: [1, 2, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0].
[ Info: Found new satisfying root: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0].
[ Info: Found new satisfying root: [1, 2, 2, -1, 2, -2, 1, 0, 0, 0, 0, 0, 0, 1, 0].

and then the process breaks off.

**Comment by bottine** [comment]
Can you try on the branch `number_fields_maybe` ? i.e. do `git checkout number_fields_maybe` and try doing the same.

... I get an error there, let me see

**Comment by sashakolpakov** [comment]
This fails at the diagonalisation step: 

Vinberg_Algorithm(m)

produces 

AssertionError: We have a diagonalization
diagonalize(::SizedArray{Tuple{15,15},Int64,2,2,Array{Int64,2}}) at util.jl:146
diagonalize(::Array{Int64,2}) at util.jl:53
signature(::Array{Int64,2}) at util.jl:45
assert_sig_n_1_matrix(::Array{Int64,2}) at hyperbolic_lattices.jl:60
HyperbolicLattice(::Array{Int64,2}) at hyperbolic_lattices.jl:69
Vinberg_Algorithm(::Array{Int64,2}; cone_roots::Array{Any,1}, rounds::Nothing) at vinberg_algorithm.jl:201
Vinberg_Algorithm(::Array{Int64,2}) at vinberg_algorithm.jl:201
top-level scope at run_algorithm.jl:19

**Comment by bottine** [comment]
After some more investigation, it's actually the part checking finite volume on Coxeter diagrams that is choking here… I think I'll have to rewrite it to be less memory hungry!
